[workspace]
members = [
    "app",
    "app_macro",
]
resolver = "3"

[profile.release]
strip = true
lto = true

#ref. https://github.com/tauri-apps/muda/pull/341
[patch.crates-io]
muda = {version = "0.17.1", git = "https://github.com/rmakestrash-jpg/muda.git", rev = "350b9bda3eabd7327e1a2592019cd33e7f559d44"}
egui_tracing = {git="https://github.com/grievouz/egui_tracing.git", rev = "7e919956ef885c2f6c3f4f096b088f160a69d101"}

#[patch.forgejo-code-rust]
#network-handler = {path = "../network-handler/network-handler"}
#network-handler-listener-osc-tokio = {path = "../network-handler/network-handler-listener-osc-tokio"}
#vrchat_osc = {path = "../vrchat_osc"}